### ISSUE TITLE
Use Total Callouts in a CalloutPack

### ISSUE THREAD

**Issue by Raph67110** [theonethatownz/Total-Callouts#1]
Hello,
Let me introduce myself, I am currently making callouts on LSPDFR. I'm French, so I would love to make a plug-in with your awesome callouts inside, which I could translate into French.
I prefer to ask permission before posting anything. Of course, you will be credited in the plug-in, that's the least of it.
Thank you in advance for your response, I would be delighted to answer all your questions.
 
cordially,
Raph67110

**Comment by lsvMoretti** [comment]
Hi Raph,

That's no issues from me! I've not been doing LSPDFR stuff for a while. I
have considered making some new plugins though.

**Comment by Raph67110** [comment]
Thanks !
